### ISSUE TITLE
fludashboard.runwsgi errors

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#101]
fludashboard.app is running fine on both development and production install.
With the runwsgi, on the other hand, I had some issues.

When running as normal user, after checking and downloading the data files, I get the following error:
```
[II] DONE!
[II] Starting update data [OK]
[II] Starting app ...

Error: Error: '/tmp//fludashboard_error.log' isn't writable [PermissionError(13, 'Permission denied')]
```

When running as sudo, I get this one:
```
[II] Starting update data ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "fludashboard/app.py", line 8
    def update_data_files(update_data: bool):
                                     ^
SyntaxError: invalid syntax
[II] Starting update data [OK]
[II] Starting app ...
```

**Comment by xmnlab** [comment]
> When running as normal user, after checking and downloading the data files, I get the following error:

ok .. I will think a way to put this log into the package root folder

> When running as sudo, I get this one:

when you use sudo, the system automatically use another python ... and probably a version before 3.4 

maybe you can use sudo -e to run .. but it is not a good way ... I will fix the problem and you should run with normal user
