### ISSUE TITLE
TAG 0.3.0

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#103]
@marfcg 

can we create a 0.3.0 tag for the master branch?

the idea is try create a first package to validate the packaging workflow ... 

and when the issue #96 we create the TAG 0.3.1

What do you think?

**Comment by xmnlab** [comment]
Thanks!

**Comment by xmnlab** [comment]
@marfcg 

sorry ... my bad ..  the tag should be v0.3.0 (usually is written with the prefix v) .. I update the tag name :)

thanks!

**Comment by xmnlab** [comment]
@marfcg 

for some upload issues I needed to increase the version to 0.3.1

https://pypi.python.org/pypi/fludashboard

I'm sending a new PR with this version change .. and after merge I will create the new tag.

**Comment by marfcg** [comment]
I've tested the installation with pip and all went well, by the way. \o/

**Comment by xmnlab** [comment]
:D great!

**Comment by xmnlab** [comment]
@marfcg 

the packaging failed .. I will take a look why that happens ... and when that is fixed I will close this issue.

**Comment by xmnlab** [comment]
https://anaconda.org/conda-forge/fludashboard
