### ISSUE TITLE
module runwsgi

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#105]
@xmnlab How is the module fludashboard.runwsgi intended to be used?

If I just run `python -m fludashboard.runwsgi`, I notice two things:
- the data is always downloaded (which is nice since it would be updated automatically, I'm just checking whether this is the expected behavior);
- the system is not generated in any address/port. Is it intended to be run inside a webserver, right? If so, could you provide me with the basics (links pointing in the direction is already a start) so I can set up the server to use it accordingly. I have sent the updates to Oswaldo, which I'm pretty sure knows how to handle it, the request for some pointers is for my own information. I've browsing through http://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html in the meanwhile.

 Thanks!

**Comment by xmnlab** [comment]
@marfcg 

I though the runwsgi should be used in a docker container, so generally when we start the app, probably the data is not there ... for `python app.py` the app download data just if it is not there or update data when necessary. I should to improve this approach soon.

for runwsgi, these are the configs:

```
WSGI_HOST="0.0.0.0"
WSGI_PORT="8000"
```
so the address of the app is the same address of the container and it is allowing request from external address ... and the port should be 8000

**Comment by xmnlab** [comment]
it is configured to use 4 workers .. but if you think we can increase or decrease this workers we can change it.

these workers are instances of the app .. this is used for concurrent requests.

**Comment by marfcg** [comment]
I've added Oswaldo (https://github.com/ogcruz) to the @FluVigilanciaBR/deployment team. I believe he should be part of this discussion since he is helping me with the deployment at our server. I have brought him up to date we the latest developments of the engine.

**Comment by xmnlab** [comment]
Great!

welcome @ogcruz!

**Comment by xmnlab** [comment]
I want to create a settings file external from the package structure .. maybe ~/fludashboard.conf ... something like that ... so we can change the parameter of the application with no modification in the settings file in the package structure.

**Comment by marfcg** [comment]
Sounds like a good plan.

**Comment by xmnlab** [comment]
done.
