### ISSUE TITLE
Prototype bugs

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#11]
- [x] the table tile should be "Incidência na semana epidemiológica XX".

**Comment by marfcg** [comment]
-  [x] The color code shown on the map corresponds to the previous week, not the selected one.

**Comment by marfcg** [comment]
- [x] Allow for year selection

List of available years can be fetched from data file as

``` python
list_of_years = []
for col in df_incidence.columns:
   if 'SRAG' in col:
      list_of_years.append(int(col.replace('SRAG','')))
```

**Comment by xmnlab** [comment]
- [x] data calls using queue library;
- [x] change data table to datatables lib [1];
- [x] when the week slider is moved with the arrow keys the visualizations do not update;

[1] https://datatables.net/
