### ISSUE TITLE
Remove br-states.json from the package

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#112]
Remove br-states.json file (8,3M) from the package.

**Comment by marfcg** [comment]
@xmnlab 
With the inclusion of this file in the data repo, is this issue closed?

**Comment by xmnlab** [comment]
Yes! :)

**Comment by marfcg** [comment]
I've just noticed we currently have it at fludashboard/data and fludashboard/static/data
Can I safely remove them?

**Comment by xmnlab** [comment]
You're right .. I haven't noticed that .. I you can .. I will take a look
here .. just a sec


2018-05-09 15:55 GMT-04:00 Marcelo F C Gomes <notifications@github.com>:
