### ISSUE TITLE
Template for temporary unavailable website

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#115]
During periods of cross-validation with the MS, as well as system's error correcting, it is important to have a webpage that can be set with a "site temporary unavailable for technical issues" disclaimer.

This page should be generated by admin whenever necessary.
Optimally, it should also be a fall-back whenever the system has been shutdown for other reasons not triggered by the admin him/herself.

- [x] Create text template
This page should use the same template as the help webpage. That is, keeping the identification bars, but displaying the "temporary unavailable" warning.
- [x] Change code so that admin can load "unavailable" or "model" as the main page.

**Comment by xmnlab** [comment]
@marfcg 

> Change code so that admin can load "unavailable" or "model" as the main page.

what model means here?

**Comment by xmnlab** [comment]
I have already created pages for 404 (page not found), 403 (Access forbidden) and 500 (Server error) error.

**Comment by marfcg** [comment]
"model" would mean the page with the system running in its current state.
Yeah, It's not the best word to describe it... but it was what came to mind at the moment, in the lack of a better term.

**Comment by xmnlab** [comment]
ok initially we can do a simple admin access with fixed password .. when you have more defined our infrastructure we can create a user form to create new user and change password functionality.

is it ok for you?

**Comment by marfcg** [comment]
At the moment we don't need a user/password access to the website, it can still be publicly accessed (hopefully it will forever be).
What I had in mind is a way for the system admin to toggle the website between "up-and-running" to a page with a warning that the website is "temporarily unavailable for maintenance".

Unless we can have a mix of both: during maintenance the current version is only accessed by user/password, with the "unavailable" warning for the general public, and when everything is fine the page is accessible to any visitor without the need to enter user and password.

Is it possible?
We can set schedule a chat so that I can explain myself better.

To give a picture of what is the issue:
The team at the Ministry asked us to put the page down until we meet with them again to go over the new functionalities. So, during this period, instead of the current stable version, whoever go to the InfoGripe website should see a webpage with the "temporarily unavailable" warning. 
Once we have gone over all the details with them and they give us the green light, than we can take down the "unavailable" and bring the stable version back online.

**Comment by xmnlab** [comment]
> We can set schedule a chat so that I can explain myself better.

sure! if you want to talk now .. it is ok for me .. 

practically .. if you want a online switch to change this page .. we will need a admin page with password .. but   if you want to change a settings file with a switch variable ... we can do it easily

**Comment by xmnlab** [comment]
to switch the initial page to the unavailable page, use this in the .flu.yaml file:

```yaml
APP_AVAILABLE: false
```
