### ISSUE TITLE
Very high threshold missing

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#121]
Since migration to database structure, the very high threshold is no longer being drawn on the chart.

**Comment by xmnlab** [comment]
can you send a screenshot?

**Comment by marfcg** [comment]
Here it goes for SP (territory_id = 35)
According to the database table mem_report, we have:
very_high_threshold = 0.533

I'm sending you a print from the current state of my development branch, in which I changed the way the upper bound for the background is set:
https://github.com/marfcg/fludashboard/commit/fc34321b33b33523cb11b946637c7919cd5419cb

![sp-2017-very_high_threshold](https://user-images.githubusercontent.com/8262366/36043597-f5c17c6e-0db6-11e8-9477-7621c9c46264.png)

**Comment by marfcg** [comment]
At the current state at the upstream branch, for SP, the upper boundary for the red background is at 1.02*very_high_threshold, and the dashed line for the very_high_threshold is missing.
https://github.com/FluVigilanciaBR/fludashboard/blob/64fb7788f2b6e59fe65340ca30ad7bfe9f8792d2/fludashboard/libs/views.py#L183

**Comment by xmnlab** [comment]
for a unknown reason .. this line is hidden on css file :S

2018-02-09 14:35 GMT-04:00 Marcelo F C Gomes <notifications@github.com>:

**Comment by xmnlab** [comment]
I think the idea was to hidden the typical very high line (of the area) ..
sorry about the mistake ...

2018-02-09 14:56 GMT-04:00 Ivan Ogasawara <ivan.ogasawara@gmail.com>:

**Comment by marfcg** [comment]
The red line that appears at the top of the background, right?
Yeah, that would make sense.

So, just removing the following block from custom.css:
```
.c3-shapes.c3-shapes-very-high-threshold.c3-lines.c3-lines-very-high-threshold > path {
  stroke: rgba(255, 0, 0, 255) !important;
  opacity: 255 !important;
  visibility; hidden; 
```
Does the trick without any side effects, correct?

Regarding the top line, one alternative is to set the y_axis upper limit at the same value that I set for the background. In this way, there wouldn't be a problem having that thin red line there and we would also avoid the white background when the curve peak is close to that value (as seen in the snapshot).

At views.py:
```
    # cheating: using a new field corredor_muito_alto just for plotting
    df['typical_very_high'] = df[['very_high_threshold', 'ci_upper', 'value', 'typical_high']].max().max() * 1.02
```

My question, then, is how to set the y_axis limits. ;)

**Comment by xmnlab** [comment]
> df['typical_very_high'] = df[['very_high_threshold', 'ci_upper', 'value', 'typical_high']].max().max() * 1.02

much better :+1: 

> My question, then, is how to set the y_axis limits. ;)

there is a good question hehe

here [1] we can see a way to use a specific range .. in our case we need a range from the csv data.

[1] http://c3js.org/samples/axes_y_range.html
