### ISSUE TITLE
Data tables

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#13]
@fccoelho, @marfcg 

when the data table will be showed? what information should be displayed?

Cases:
1. State NO selected, week == 0 (whole year)
2. State NO selected, week > 0
3. State selected, week == 0 (whole year)
4. State selected, week > 0

**Comment by xmnlab** [comment]
For the item 4, the table shows the incidence value for all State for the selected week.

**Comment by marfcg** [comment]
1. Total number of cases in the selected year for each State + same data for the Country
2. Number of cases in the selected week for each State + same data for the Country
3. Total number of cases in the selected year for selected State
4. Number of cases in the selected week for selected State.

**Comment by xmnlab** [comment]
@marfcg 

In the cases 1 and 3, should these work just for whole year view (https://github.com/FluVigilanciaBR/fludashboard/issues/8#issuecomment-252091150), right?

**Comment by marfcg** [comment]
> In the cases 1 and 3, should these work just for whole year view (#8 (comment)), right?

Exactly. :+1:

**Comment by xmnlab** [comment]
- [x] Total number of cases in the selected year for each State + same data for the Country
- [x] Number of cases in the selected week for each State + same data for the Country
- [x] Total number of cases in the selected year for selected State
- [x] Number of cases in the selected week for selected State.
