### ISSUE TITLE
Geopolitical regions aggregate

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#134]
Display data aggregated by geopolitical regions (Norte, Sul, Nordeste, ...).

The toggle is already on the index.html and dashboard.js file, but the later and the rest of the system must be updated to properly show the corresponding data.
Several changes to that effect have been made already, but it's not complete yet.

**Comment by xmnlab** [comment]
ok .. I will take a look ;)

**Comment by xmnlab** [comment]
in the code I am changing the label for territory type (state, region, etc) by theirs ID on database.

**Comment by xmnlab** [comment]
There are new fields in the clean_data_epiweek_weekly_incidence_w_situation table (ADNO, PARA1, PARA2, PARA3) .. what these fields mean?

**Comment by marfcg** [comment]
Those will be used to plot the accumulated number of cases and incidence of SRAG caused by Adenovirus, Parainfluenza1, Parainfluenza2, ...).

This will be a new panel with those time series on a multipanel way, like this:
https://i.stack.imgur.com/PWkZq.jpg

Looking at the D3-based graphs, I couldn't find examples in the gallery, though...

**Comment by marfcg** [comment]
https://github.com/FluVigilanciaBR/fludashboard/issues/134#issuecomment-367765275 has moved to #136 
The current issue has been successfully addressed.
