### ISSUE TITLE
Etiological agents panel

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#136]
Include an additional panel with time series for Flu A, Flu B, Adenovirus, VSR, Parainfluenza 1, Para 2, Para 3, Outros. Since they are usually small, it would be better to keep on separate plots on the same panel
Also, on a single plot:
inconclusive, not tested, delayed (aguardando resultado), positive cases, negative, testing ignored

On this panel, there will be no estimates, just already reported (as in the age dist. chart).

I'll create a Notebook with an example.

**Comment by xmnlab** [comment]
great!

**Comment by marfcg** [comment]
@xmnlab 
when you have the time, take a look at the notebook https://github.com/FluVigilanciaBR/fludashboard/blob/development/Notebooks/Etiological_agents_timeseries.ipynb

**Comment by marfcg** [comment]
We need to move the plot title "Exames laboratoriais [...]" to the panel title, like on the other ones.

**Comment by xmnlab** [comment]
ok
