### ISSUE TITLE
Opportunity panel

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#138]
Create a panel to show as boxplots the several opportunity observations:
 - Digitalization;
 - Notification;
 - Result;
 - Terapy;
 - ...

I'm working on the dataset extraction and database update.
I couldn't find any example of boxplots with C3.js D3-based graphs.
The goal is the plotly style, if possible:
https://plot.ly/python/box-plots/

**Comment by marfcg** [comment]
As on #136 , I'll prepare a notebook example.

**Comment by xmnlab** [comment]
ok .. maybe we can use plotly js: https://plot.ly/javascript/box-plots/

**Comment by marfcg** [comment]
I couldn't find a way to change the boxplot hover labels. That aside, it delivers the request made by the MH team.
PS: I've made use of cufflinks library to test it's functionality. If you think it is not necessary for production, feel free to bypass it.

**Comment by marfcg** [comment]
We need to move plot title "Distribuição de oportunidades [...]" to the panel title, like on the other ones.

**Comment by xmnlab** [comment]
OK
