### ISSUE TITLE
States / Regions

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#14]
We should include in the prototype a select option that allows the user choose Region or State selection mode?

**Comment by marfcg** [comment]
Yes, I believe so. Either as a checkbox / button or separate tab.

**Comment by xmnlab** [comment]
maybe if the system allows both method at same time .. that will be confusing .. will be confusing in the map to display the colors .. and will be confusing to select the desired choice.

what do you think?

**Comment by marfcg** [comment]
At the same time would definitely be a mess.
I would go for something like this:
- if "regions" method is selected, the map is shown with its boundaries defined by the regions (State divisions could be shown as lighter gray lines in contrast to darker lines representing regional borders). 
- When State is selected, we keep it as it is right now.
