### ISSUE TITLE
Contingency plan alert levels

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#151]
Per request by the MH, we need to the change the map colors based on the contingency plan instead of what is currently used at the seasonal view mode.
The details and an example is shown in the notebook https://github.com/FluVigilanciaBR/fludashboard/blob/development/Notebooks/Season_color_new_specs.ipynb

Notice that this map will be independent of dataset and scale selected by the user.
It will only depend on the year and territory selected.

To be honest, I would rather create a new view mode called "contingency plan", which would be pretty much identical to the seasonal one. The only changes would be that (1) the map color criteria would follow the rules described on the notebook, and (2) the year will be locked to the latest epiyear in the database. This would be the default view mode upon entering the website.
Therefore, we would have three view modes: weekly ("Detalhado (semana)"), seasonal ("Temporada (ano)"), and contingency plan ("Plano de contingência atual")

This way, we do not lose the information generated for the previous seasons regarding what was the activity level during the seasonal compared to what is expected and we would still provide the info requested by the MH.

**Comment by xmnlab** [comment]
great! I will take a look!

**Comment by xmnlab** [comment]
@marfcg 

the difference between resumed (year) and contingency will be just the colors and the controls? 
the data should be the same? I mean, we have 6 panels we will keep showing this panels with the same data like in resumed view?

**Comment by marfcg** [comment]
Yep!
Main differences:
- Colors for the map following contingency plan criteria;
- For the other panels, use same data shown on the resumed view, but locked to most recent epiyear.

The contingency colors don't make sense for previous years, since it changes according to the data on recent weeks.

**Comment by marfcg** [comment]
The contingency plan map is having issues distinguishing the orange and red color, for some weird reason... The values are calculated correctly, but when it is 3 ("Nivel 1" by MH nomenclature, which should be orange #ff7700), the color shown is red, as when contingency=4 ("Nivel 2", which is in fact red).
I've tried on Firefox and on Chrome, with same results...

**Comment by marfcg** [comment]
The latest PR https://github.com/FluVigilanciaBR/fludashboard/pull/160 fixes the bug reported at https://github.com/FluVigilanciaBR/fludashboard/issues/151#issuecomment-387317013
It is still not directly in the DB, but provides a temporary fix.
I believe we are ready to release a new version.
The next one will be with all calculations in the data update phase. That is, all alert levels will be calculated outside fludashboard and stored in the DB. fludashboard will only need to read the corresponding table.
This will increase its speed considerably.
