### ISSUE TITLE
Wrong panel titles when changing view mode, dataset or scale

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#153]
If a UF/region/regional is selected, when the user change any of view mode, dataset, or scale, the panel titles change back to "Brazil", even though the data shown is still the one corresponding to the previously selected area.

Example:
On the main page, select any UF. Then, change the dataset to SRAGFLU or the scale to CASOS. The data will correspond to the selected UF, but the title of each panel will change to "Brazil".

**Comment by xmnlab** [comment]
@renomoto can you take a look in this issue?

@marfcg and I can provide any support to clarify any doubt.

**Comment by marfcg** [comment]
@xmnlab do you know if @renomoto is following this issue?
We are presenting the system to the ministry of health on May 7th. It would be good to have this sorted out by then.

**Comment by xmnlab** [comment]
I have not received any updates. I will take a look at this one :+1:
