### ISSUE TITLE
configure travis-ci

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#16]
@fccoelho, @marfcg 

Could you configure travis-ci for the fludashboard?
Or if you can create a team and add me as a member I can do it.

**Comment by marfcg** [comment]
@fccoelho can you handle this one?
I have no clue what this is... :stuck_out_tongue: 
Alternatively, can any of you point me on its direction?

**Comment by xmnlab** [comment]
maybe this can help you:

https://www.youtube.com/watch?v=s_vjTg23G-o

this will be used to test each pull request before the merge.

**Comment by fccoelho** [comment]
Done. @xmnlab, can you create the `travis.yml` and push it to activate it?

**Comment by xmnlab** [comment]
it is already on the repo :)
