### ISSUE TITLE
Release numbering

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#17]
@xmnlab I have never worked with version numbering before, so please bear with me on this one...
I have made several changes on the codes that generate the data we are using here.
It will make some calculations here easier (such as weekly incidence per age bracket), as well as comply with the epidemiological week as defined in Brazil.
On the other hand, some columns have been renamed, such as isoyear and isoweek -> epiyear and epiweek

Those changes would need to be rolled over to the codes here.
Now, before I update the notebooks to demonstrate the new structure and push it up: do I mess around with version numbering or I just leave it to you?

**Comment by xmnlab** [comment]
@marfcg just do it :)

I will isolate the fludahsboard/prototype folder .. and I'm working in a new one: fludashboard/fludashboard ... so I think we don't need to worry about the version number yet. 

I think that if we just create a tag, as such "prototype", should be enough.

What do you think?

**Comment by xmnlab** [comment]
I just don't have permission to create a tag .. can you create it?

**Comment by marfcg** [comment]
Ok. I'm logging out for the day. I'll work on the notebooks and as soon as they're ready I'll push'em up.
