### ISSUE TITLE
map chart legend

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#28]
@marfcg 

Should the map chart show a color legend panel?

**Comment by marfcg** [comment]
Yes, it would be good to have one.
Do you need the text for those?
I believe they are writen either on the notebook or on one of the issues
(I'm currently traveling  with low Internet connectivity).
Let me know if you need them and for which panel (detalhado /resumo).

---

*Sent from mobile device. My apologies for eventual typos.
Marcelo Ferreira da Costa Gomes
Programa de Computação Científica
Fundação Oswaldo Cruz
PROCC/FIOCRUZ

**Comment by xmnlab** [comment]
Great! thank you.

Should be the text: 
- 'Baixa';
- 'Epidêmica';
- 'Alta';
- 'Muito alta'

?

**Comment by marfcg** [comment]
Yep, that's pretty much it.
Just for completeness sake:
If the legend is to have a title, it should structured as:

[Title] Nível de atividade:
- Baixa;
- Epidêmica;
- etc.

If it is easier/cleaner without title, than just add a prefix "Atividade" before each level, i.e.:
- Atividade baixa;
- Atividade epidêmica;
- etc.

**Comment by xmnlab** [comment]
done (using title)
