### ISSUE TITLE
Create notebooks with example visualizations

### ISSUE THREAD

**Issue by fccoelho** [FluVigilanciaBR/fludashboard#3]
@marfcg , since you are the one which knows best these data, could you add some Notebooks with example visualizations to the project? This way @xmnlab  can build upon these examples.

**Comment by marfcg** [comment]
I have pushed an example for the incidence plot using Python's matplotlib in 639b35e
This plot shows:
- Current/selected season incidence
- Colored background with typical activity
- Intensity thresholds

**Comment by fccoelho** [comment]
Great @marfcg !

@xmnlab , I think you can start to play with this ideas . Trying to integrate them on a web app we can interact with. We can add the maps afters the visualization of the series is done or at least working.

**Comment by xmnlab** [comment]
great @fccoelho! I'm starting to check out that.

**Comment by xmnlab** [comment]
@fccoelho, @marfcg 

can you provide a notebook with sex/age distribution chart?

**Comment by xmnlab** [comment]
or just the data with information about the columns.

**Comment by marfcg** [comment]
Will work on it.

**Comment by xmnlab** [comment]
@marfcg some new? :)

**Comment by marfcg** [comment]
Dear all,

Sorry for the long silence. The reestructuring of the data files is taking
longer than I expected.
The reason is that I'm including the delay correction flow so that the next
batch is already with the full information for the website.
I have opted for that in order to avoid having to rewrite file reading yet
again once we had those estimates.

You can track the latest implementations at  FluVigilanciaBR/seasonality

## Cheers,

*Sent from mobile device. My apologies for eventual typos.
Marcelo Ferreira da Costa Gomes
Programa de Computação Científica
Fundação Oswaldo Cruz
PROCC/FIOCRUZ

**Comment by marfcg** [comment]
Okay, finally pushed the new notebook for the incidence time series.
It's in the Notebooks branch https://github.com/FluVigilanciaBR/fludashboard/commit/08c8b14e6187285e3d02eaa54c3268c99c363bd3

**Comment by xmnlab** [comment]
great!

I've seen it now, thanks! I will see it with more attention tomorrow. :+1:

**Comment by marfcg** [comment]
Please take a look at https://github.com/FluVigilanciaBR/fludashboard/commit/0e77a9ac9d488b5086e2bf86f05fe00c1cd15902
Age distribution histogram included in https://github.com/FluVigilanciaBR/fludashboard/blob/master/Notebooks/incidence_with_indicators.ipynb

I believe we have everything ready for the weekly panel (aka "Detalhado" https://github.com/FluVigilanciaBR/fludashboard/issues/1#issuecomment-252327525)

**Comment by xmnlab** [comment]
great! thank you!

**Comment by marfcg** [comment]
@xmnlab Athough this issue is already closed, I have pushed a recent commit to Notebook branch which incorporated info for the summary panel (aka Resumido at https://github.com/FluVigilanciaBR/fludashboard/issues/1#issuecomment-252327525). I've referenced this issue to keep it properly documented.

**Comment by xmnlab** [comment]
Great! I will see that tomorrow (I'm finishing the refactoring the
front-end codes...)
