### ISSUE TITLE
Seasonal levels

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#33]
In the current version, at the summary view ('Resumido'), the levels are not being correctly labelled for the yellow, orange and red levels.
According to ECDC's criteria we are using, orange and red levels should be triggered when the high or very high thresholds are crossed (https://github.com/FluVigilanciaBR/fludashboard/issues/1#issuecomment-247668389).
Currently, those levels are being activated only when the very high threshold is crossed for the defined number of weeks.

Also, the yellow level should be used when only the epidemic threshold have been crossed, but not the high or very high. Currently, this level is being used when only the very high level hasn't been crossed but any of the other two has.

Ref:
At https://github.com/FluVigilanciaBR/fludashboard/blob/master/fludashboard/static/js/srag_map.js#L231-L247

```
/**
* Get the alert level color using the follow criteria:
*
* Red (level 4) if the incidence was above the high threshold for at
*  least 5 weeks;
* Orange (level 3) if above the high threshold from 1 to 4 weeks;
* Yellow (level 2) if crossed the epidemic threshold but not the high one;
* Green (level 1) if it did not cross the epidemic threshold.
* @param {dict} d - total number of alert occurrence
* @return {number} alert level
*/
getAlertLevelForWholeYear(d) {
  if (d[4] >= 5) return 4;
  if (d[4] >= 1 && d[4] < 5) return 3;
  if (d[2] >= 1 || d[3] >= 1) return 2;
  return 1;
 }
```

If I read the code correctly, for 4 and 3 we should have something like d[3]+d[4] in the inequalities, while for 2 we should only have d[2] >= 1 alone.

**Comment by xmnlab** [comment]
Ok, I will see that! :)

**Comment by xmnlab** [comment]
@marfcg,

you are right :)

I think the code fixed should be:

``` javascript
function getAlertLevelForWholeYear(d) {
  var high_threshold = d[4] + d[3];

  if (high_threshold >= 5) return 4;
  if (high_threshold > 1) return 3;
  if (d[2] >= 1) return 2;
  return 1;
}
```

I also will change the code to use properly the L# (L0, L1, L2, L3) fields properly too.
