### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#34]
I believe we don't need the population file https://github.com/FluVigilanciaBR/fludashboard/blob/master/data/PROJECOES_2013_POPULACAO-simples_agebracket.csv any more. 
It is not needed at any panel and neither is it needed to complement the info on the other input files.

We should look into the codes to remove any call to that file.

**Comment by xmnlab** [comment]
Ok! I will see that :)
