### ISSUE TITLE
Brazilian epidemiological week system

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#36]
When setting the current week to show on the panel upon loading, we need to use the Brazilian epidemiological week definition, which is different from the ISO calendar one.

For that purpose, we created a python module episem.py based on Oswaldo G. Cruz's R function to extract the epiweek from a given date.
Using ISO calendar to set the week can potentially lead to errors.

There's a new notebook showing how to use episem:
https://github.com/FluVigilanciaBR/fludashboard/blob/master/Notebooks/Brazilian_epiweek.ipynb

The module is also included in the Notebooks folder.

PS: feel free to adapt/port the module to your needs.

**Comment by xmnlab** [comment]
great, I will take a look 👍

**Comment by xmnlab** [comment]
done
