### ISSUE TITLE
Week selector

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#38]
Week selection is working flawlessly with the slider.

Nonetheless, there are a few enhancements that would be great to have:
- When moving the slider, continuously change the value on the box so the user can check where he is before releasing mouse button;
- Allow week selection by entering value in the box directly;
- Be able to use cursor to move slider.

I'm not familiar with js and JQuery, but it seems that the following entries might deal with those issues:
http://stackoverflow.com/questions/24819768/change-a-text-boxs-value-continuously-as-a-html5-range-slider-moves
http://stackoverflow.com/questions/19483469/updating-jquery-ui-slider-from-text-box-value-on-change

I have tried to look into the code to implement those, but my illiteracy with the language blocked me... :stuck_out_tongue_closed_eyes:

**Comment by xmnlab** [comment]
Thank you a lot for the examples!
