### ISSUE TITLE
check the incidence chart size

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#47]
@marfcg @fccoelho 

can you check if the incidence char size is good?

I think when the appt shows the estimated cases and CI lines the chart size is very small to understand these lines.

What do you think?

**Comment by marfcg** [comment]
Sorry for the long delay on this one.
Maybe you could try increasing the height of both upper panels (map and incidence chart) a little bit. If it is relatively simple to tweak with this setting, feel free to point to where it sits in the code. This way I can play around with it.

But it is readable anyway. It's definitely a minor issue. 
Great job!
