### ISSUE TITLE
Supported languages

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#5]
@fccoelho, should this application supports multi-language?

**Comment by fccoelho** [comment]
Not necessarily. Buy it doesn't hurt to plan for it.

Em 09/09/2016 21:28, "Ivan" notifications@github.com escreveu:

**Comment by xmnlab** [comment]
ok!

initially, should it be written in English or Portuguese?

**Comment by fccoelho** [comment]
I normally do it in English and then add the translation to Portuguese. That makes it easier for non-portuguese speakers to work with it and add other translations. @marfcg  and @claudia-codeco , do you think it is worth preparing for internationalization at this stage?

**Comment by marfcg** [comment]
I believe it's a good move to have it.

By the way, we are going to the Brazilian Influenza meeting in the week of
Sept 26-30.
Do you think it's feasible to have a prototype by then? Map and incidence
curve only, at the moment, would do. I'm going to prepare a video with the
map, but it would be nice if we could show the website prototype as well.
For that, Portuguese is the norm, though.

## Cheers,

*Sent from mobile device. My apologies for eventual typos.
Marcelo Ferreira da Costa Gomes
Programa de Computação Científica
Fundação Oswaldo Cruz
PROCC/FIOCRUZ

**Comment by xmnlab** [comment]
Initially, I'm doing a prototype to validate the front-end libraries (I
hope to finish that this week). When the first version is ready, I will do
the pull request (https://github.com/xmnlab/flu
dashboard/tree/master/prototype).

Next, I will use the test dataset available in "/data" directory.

Maybe would be helpful if we have the information about all fields that
will be used in the charts, like the input and output data for the charts,
example: for chart 1 we need the dataset "A", using the fields A1, A2 and
A5 and the result shows the sum of (A1-A2/(A5^4)).

If you want, should be included some filters that would be good to apply in
the charts.

**Comment by xmnlab** [comment]
@fccoelho, @marfcg 

for the prototype, we used Portuguese language. 

For the next step, should we continue using Portuguese?

**Comment by xmnlab** [comment]
The next release is been done in Portuguese language.
