### ISSUE TITLE
Unittest fail

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#55]
Although the system is working, the unittest is returning a failure due to file not found. The weirdest thing is that the files ARE there...

I have accepted the merge since the issue with the new data structure has been solved and we now have the age distribution by gender working nicely for the detailed panel. We need to check what's going on with the unittest, the app itself is reading the data as it should...

**Comment by xmnlab** [comment]
@marfcg I'm working to solve this problem.

the problem is in setup.py and path references.

I have had some progress but not fineshed yet.
