### ISSUE TITLE
General review

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#62]

**Comment by xmnlab** [comment]
- [x] As curvas de tendência (os "corredores") e os limiares possuem valor até a semana 52, mesmo quando os dados de casos não estão presentes. Ficaria só a curva de incidência truncada, estas outras são desenhadas até o final;
- [x] em summary: Na tabela a situação "estável" e "incompleto" está invertida;
- [x] check incidence curve example with state where estimates are not available (e.g. Rondônia, year 2016, week 32);
- [x] resolve map alert color when week defined is not in the srag data (shows grey instead);
- [x] in summary panel table: when the situation is incomplete, the incidence value should initiate with a asterisk (*) and when the situation is estimated, the incidence value should finish with the confidence interval;

**Comment by xmnlab** [comment]
@marfcg do you see any other problem to be fixed? or can we close this issue?

**Comment by marfcg** [comment]
I'll do another pass to check and either add another bullet point or close it. Thanks a lot for the updates! ;)
