### ISSUE TITLE
Documentation tab

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#64]
@xmnlab Create another page as a tab/button for documentation regarding color scheme criteria.
It would be a simple doc page where we specify:

For the detailed panel:
- [x] color scheme for the map,
- [x] thresholds for the incidence chart,
- [x] background areas for the incidence chart,
- [x] age distribution chart,
- [x] incidence table,

For the summary panel:
- [x] color scheme for the map,
- [x] age distribution chart,
- [x] incidence table,

Layout possibilities (please leave your opinion or alternative):
- Simple formatted text page
- Image with text boxes for each block (map, incidence chart, table, age dist.)

I will prepare the text for each while we think about the layout.

**Comment by xmnlab** [comment]
maybe would be nice add the explanation video in this doc

**Comment by xmnlab** [comment]
must the documentation be displayed in portuguese?

**Comment by xmnlab** [comment]
would be better a separated page with all documentation or a float panel for each chart (we can help icons to open each panel)?

**Comment by marfcg** [comment]
I have produced both Portuguese and English versions. But, for the site we should use Portuguese as the default.

The idea of help icons is nice. I'm just not sure the text is small enough. But it's definitely interesting.
We could have the full info on a separate page and the help icons with the corresponding text and a link to it's section in the help page.

I have inserted the video in the README_pt-br files. Although it does not show the embedded video when opening the rst file inside github, the generated html has it.

**Comment by xmnlab** [comment]
> I have produced both Portuguese and English versions. But, for the site
we should use Portuguese as the default.
>

OK

> The idea of help icons is nice. I'm just not sure the text is small
enough. But it's definitely interesting.
> We could have the full info on a separate page and the help icons with
the corresponding text and a link to it's section in the help page.
>

OK

> I have inserted the video in the README_pt-br files. Although it does not
show the embedded video when opening the rst file inside github, the
generated html has it.
>

maybe here [1] you can find some idea.

[1] http://stackoverflow.com/questions/11804820/embed-a-you-tube-video
