### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#7]
What kind of documentations will be needed to this project?

**Comment by fccoelho** [comment]
@xmnlab initially the documentation should be kept to a minimum, since the main goal is to finish the prototype. So I think we should document 
- [x] installation and deploy procedures (This can go on the Readme)
- [x] docstrings where necessary

**Comment by xmnlab** [comment]
@fccoelho @marfcg 

can you configure the readthedocs service to work with the repo?

I think the url should be something like that: https://fludashboard.readthedocs.io

or just create a team and add me as a member and I do it.

**Comment by fccoelho** [comment]
Done. http://fludashboard.readthedocs.io/
I added @xmnlab and @marfcg as maintainers

**Comment by fccoelho** [comment]
update: @marfcg was not added because he is not a user of readthedocs... (not with this userid at least)

**Comment by marfcg** [comment]
Account created at readthedocs and linked with github

---

*Sent from mobile device. My apologies for eventual typos.
Marcelo Ferreira da Costa Gomes
Programa de Computação Científica
Fundação Oswaldo Cruz
PROCC/FIOCRUZ

**Comment by xmnlab** [comment]
In the last days, I was trying to using readthedocs with javascript code. At this moment I have no success, I will back in this issue when release 0.1 is done.

**Comment by xmnlab** [comment]
jsdoc references: http://speakingjs.com/es5/ch29.html
