### ISSUE TITLE
Add new navbar to the layout

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#73]
- [ ] inserir a barra do governo http://barra.governoeletronico.gov.br/ 
- [ ] uma barra com logo da fiocruz (exs: www.ensp.fiocruz.br/portal-ensp/ e www.ini.fiocruz.br) + EMAp-FGV;

Na pasta data há um svg com o logo da fiocruz e do procc já com as especificações da identidade visual da Fiocruz. Isso poderia ser incorporado no que hoje é a barra superior "Monitoramento de casos ..." ou na segunda barra, onde há os botões (como são de fundo branco, acho que ficará visualmente melhor aqui, na verdade).

(from @marfcg )

**Comment by marfcg** [comment]
Fiocruz navbar already has Fiocruz's logo, there's no need to fiddle with that. It's independent of EMAp-FGV and PROCC logos.

EMAp-FGV logo can be placed on dashboard's bar directly using this file:
https://github.com/marfcg/fludashboard/blob/documentation/data/logo.svg

In doing this, we comply with the regulations regarding government and Fiocruz websites with those 2 navbars, plus departments branding with the logo on the dashboard itself.
