### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#83]
@xmnlab we realized that anaconda is consuming way too much space unnecessarily.
@fccoelho suggested implementing a deploy environment using nginx webserver as in the InfoDengue suite.

**Comment by xmnlab** [comment]
> @xmnlab we realized that anaconda is consuming way too much space unnecessarily.

@marfcg  actually it is better to use miniconda .. it just install the basic of conda structure. Anaconda install a lot of packages unnecessary.

After install all pkgs you can do a conda clean [1]

> @fccoelho suggested implementing a deploy environment using nginx webserver as in the InfoDengue suite.

I think it should be good :+1: 


[1] https://conda.io/docs/commands/conda-clean.html
