### ISSUE TITLE
Dataset selector

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#84]
From the last meeting with MH, we were asked to implement the same system for three data sets:
- SRAG (as it is now);
- SRAG by Influenza ("SRAG por influenza");
- SRAG deaths by Influenza ("Óbitos por Influenza").

The datasets are ready for each case. One suggestion was to have a drop down menu or a tab for selecting each one of those.

Also, for each scenario they also want a way to change between incidence and number of cases.  Data is also ready.

**Comment by xmnlab** [comment]
@marfcg 

> The datasets are ready for each case. One suggestion was to have a drop down menu or a tab for selecting each one of those.
> Also, for each scenario they also want a way to change between incidence and number of cases. Data is also ready.

There is a long time I don't work with this project .. can you tell me what should the information I need to use as parameters?

**Comment by marfcg** [comment]
No worries. I'll polish the datasets to make it easier to parse, actually.

To show the prototype to them, I had adopted a "quick and dirty" solution of just creating new files with the exact same structure, so that I just called a different file to change from on scenario to another.

I'll provide a documentation as soon as I have the proper style set.
My idea is to have two extra columns in the timeseries and typical curve files:
- Scale: "incidence", "cases"
- Dataset: "SRAG", "SRAG-flu", "Deaths-flu"

In this way, for each scenario the system would just have to filter the data frame accordingly.

In terms of the website, we will need to change the labels accordingly:
- [x] Mapa de incidência de SRAG -> Mapa de situação de [SRAG/SRAG por Influenza/Óbitos por Influenza];
- [x] Curva de incência -> Série temporal
- [x] Eixo Y da curva de incidência e distribuição etária: [Incidência (por 100 mil habitantes) / Número de casos]
- [x] Incidência na semana epidemiológica X -> [Incidência/Número de casos] na semana epidemiológica X

**Comment by marfcg** [comment]
New file structure uploaded.
they can be found at fludashboard/fludashboard/data/new_structure/

All data files have two extra columns:
- column 'dados': 'srag', 'sragflu', 'obitoflu'
- column 'escala': 'incidência', 'casos'

Once the code is uptaded to take those into account, they can replace the ones on parent data folder and the new_structure can be deleted.

**Comment by xmnlab** [comment]
@marfcg 

I will take a look :)

PS: I created 3 new labels for priorities (low, normal, high) .. you can use it to organize the priorities of each issue :)

**Comment by xmnlab** [comment]
> Once the code is uptaded to take those into account, they can replace the ones on parent data folder and the new_structure can be deleted.

We can create a new branch called develop, and there we can already do this replace .. and when all is done you merge into the master branch. What do you think?

**Comment by xmnlab** [comment]
@marfcg 

> We can create a new branch called develop, and there we can already do this replace .. and when all is done ~~you~~ `we can merge it` into the master branch

great! when you merge the new branch I will update my env. 
Thanks!

**Comment by marfcg** [comment]
So,
In the new datasets, for any given file loaded as a pandas data frame df, each subset can be filter from those two columns.

For instance, for displaying SRAG data in terms of incidence or cases, the subset can be obtained as

```
# Subset SRAG selected by user:
dataset = 'srag'
dfslice = df[(df$dados == subset)]
# Displaying incidence:
scale = 'incidência'
dfdisplay = dfslice[(dfslice$escala == scale)]
# Displaying cases:
scale = 'casos'
dfdisplay = dfslice[(dfslice$escala == scale)]
```
So each tab SRAG, SRAG por Influenza, and Óbitos por Influenza would toggle the dataset object, while the switch Incidência / Casos would toggle scale.

The master branch still has the old file structure, without columns 'dados' and 'escala'. Only the branch development has the files with those columns.
All the remaining columns where kept as before so that there is no need to change anything else on the functions of each panel.

**Comment by xmnlab** [comment]
@marfcg 

Great! Thanks!

can you make a PR with your development branch?

**Comment by marfcg** [comment]
Oops. I thought I had already done that... it's here, now.

**Comment by xmnlab** [comment]
Thanks :)

**Comment by xmnlab** [comment]
@marfcg 

I drew a layout (draft) with  these new options. can you review it?

![detalhado](https://user-images.githubusercontent.com/5209757/31234028-db3f938a-a9bb-11e7-8de0-423a94314eb3.png)

Any considerations will be appreciated.
