### ISSUE TITLE
Time series chart (weekly panel)

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#85]
Request from the MH:
- [x] Stop notified cases line (black curve) at the most recent date considered as stable.
- When user selects previous weeks then the current one:
  - [x] black curve should stop at selected week if already stable; 
  - [x] present historical estimates for that week. For this one, I'll need to come up with a reasonable solution for the data;
- [x] Change either high activity level color or estimates color. Both are currently red;
- [x] ~In the case of upper and lower confidence interval for the estimates, present only one legend entitled "intervalo de confiança da estimativa"~  change label about CI to "Intervalo de confiança inferior[superior]";
- [x] Legend for the endemic channels (the background):
  - Green: zona de êxito;
  - Yellow: zona de segurança;
  - Orange: zona de alerta;
  - Red: zona de surto.

**Comment by xmnlab** [comment]
> Stop notified cases line (black curve) at the most recent date considered as stable.

@marfcg 

how much is most recent?

**Comment by xmnlab** [comment]
> present historical estimates for that week. For this one, I'll need to come up with a reasonable solution for the data;

@marfcg 

do you have any idea of date when you can prepare the data?

**Comment by xmnlab** [comment]
@marfcg 

> Legend for the endemic channels (the background)

Previously red area was just a region on the chart (not a data), I needed to add a red data to show it with a legend. What do you think about about the legend and the red area on the chart?

![layout](https://user-images.githubusercontent.com/5209757/31414755-828ab522-aded-11e7-9409-e6c0a8b3daab.png)

**Comment by marfcg** [comment]
Is it possible to have the legend for the lines being lines (solid/dashed accordingly) instead of color boxes?
This way, it will be easier to identify what is what.
Here goes a suggestion, with a slight change in colors (changed in the legend only).
What do you think?
For the confidence intervals, if you want to keep both for the highlighting property on mouse hover, you can label them "Intervalo de confiança inferior[superior]".
![incidence](https://user-images.githubusercontent.com/8262366/31433103-9765fb7e-ae78-11e7-8db0-b7c88d3f57ae.png)


[incidence.pdf](https://github.com/FluVigilanciaBR/fludashboard/files/1375037/incidence.pdf)

**Comment by marfcg** [comment]
> how much is most recent?

It is one week before the estimates start (it varies for each UF, dado, escala).
So, the idea is that the solid black line would only go as far as the beginning of the estimate and confidence interval curves.

From the current_estimated_values.csv file, in the column Situation, for each UF, dado and escala defined by user, the most recent stable data reported is the last one with column Situation=='stable' (equivalently, it is one week before the first (Situation == 'estimated' OR Situation == 'unknown') ).

**Comment by marfcg** [comment]
> do you have any idea of date when you can prepare the data?

I'm finishing a model today. It will have the same columns as current_estimated_values.csv plus: 'base_epiyearweek', 'base_epiyear', and 'base_epiweek', which are the epiyearweek, epiyear and epiweek with respect to which the estimates were ran.
So, if the user selected year=2017 and week=24, you can filter this data set by the columns
`(base_epiyear == 2017 & base_epiweek == 24)`
This will subset the estimates obtained on that week, for that and the previous n weeks, just as used in the current_estimated_values.csv for generating the estimates for the most current week.

Is the idea clear?

As soon as I have the data ready, I'll push it to the development branch.

**Comment by marfcg** [comment]
Data file historical_estimated_values.csv added, with structure as mentioned above.

**Comment by xmnlab** [comment]
Great! Thanks. I will take a look :)

**Comment by xmnlab** [comment]
> For the confidence intervals, if you want to keep both for the highlighting property on mouse hover, you can label them "Intervalo de confiança inferior[superior]".

great! I will do it .. I opened a issue to ask that at c3 repo but I have no answer at this moment.

so I think it is a better option for a moment.

**Comment by xmnlab** [comment]
@marfcg 

![layout](https://user-images.githubusercontent.com/5209757/31472258-a496ab84-aebb-11e7-99ba-f3936272cf0d.png)

This would be ok for a while?

I need more time to do likely your prototype .. another option should be th
e creation a box into the chart with zone legend, but I think it is not a good option, because the box could overlap the chart.

EDIT:

maybe we can do something like that: 

http://drarmstr.github.io/c3/examples/#legend/

**Comment by xmnlab** [comment]
@marfcg 

what do you think about this?

![layout](https://user-images.githubusercontent.com/5209757/31476269-9aee4b7e-aed3-11e7-9a28-a705b6d1b3f5.png)

**Comment by xmnlab** [comment]
> Is the idea clear?

so should I change the filter from `epiyear` and `epiweek` to `base_epiyear` and `base_epiweek`?

**Comment by xmnlab** [comment]
@marfcg 

> When user selects previous weeks then the current one black curve should stop at selected week if already stable;

Is it that what you want?

![layout](https://user-images.githubusercontent.com/5209757/31506461-7e9c7f5a-af45-11e7-9b72-7e3b5eab3129.png)

PS: I still using the old data.

**Comment by marfcg** [comment]
That's the idea.

Then, the estimates drawn should be the ones from the historical_estimated_values.csv with base_epiweek == week (in your example, 23). In this way, for that week we can see how good the estimates were when compared to the actual number of notified cases once the data is stable.

**Comment by xmnlab** [comment]
@marfcg 

sorry I haven't understood yet this data ... the historical csv should replace the current_estimated_values ?

with this filter:

```python

k = ['epiyear', 'epiweek', 'base_epiyear', 'base_epiweek']
df_hist2017 = df_hist[
    (df_hist.epiyear == 2017) &
    (df_hist.dado == 'srag') &
    (df_hist.escala == 'incidência') & 
    (df_hist.UF == 'BR')
].copy()

df_hist2017.sort_values(['epiyear', 'epiweek'], inplace=True)
```

I receive a list with 90 rows and ...

* epiweek range (df_hist2017.epiweek.unique()): 

```python
array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])
```
* base_epiweek range (df_hist2017.base_epiweek.unique())

```python
array([23, 24, 25, 26, 27, 28, 29, 30, 31, 33])
```

After analyse this data ... I think this file should be used just for the estimative cases .. that is right? so I should join current_estimated_values with historical_estimated_values .. is that right?

**Comment by marfcg** [comment]
Yes, the historical_estimated_values is just for the estimates, while curent_est is the most up-to-date data, used for the notification counts.
I have just updated the current_estimated_values.csv file with the one generated at the same time as the historical one. The following comment apply to this dataset.

If you compare the `df_hist2017[(df_hist2017.epiweek == 33)]` slice with the slice on df_current, you will see that for `df_current2017[(df_current2017.Situation != 'stable')]` they have exactly the same data for the common columns.

The historical file is keeping track of all estimates and unknowns generated.
Every week that a new estimation is performed, the system will update the current_estimated file and append the rows with `(df_current.Situation != 'stable')` to the historical_estimated one, with base_epiyearweek, base_epiyear, and base_week recording when it was generated.

Please let me know if it still not clear the idea here. I know it is not straightforward...

The goal of the GT-Influenza with that is to be able to retrospectively compare our estimates to what was actually notified once the data has already stabilized.

**Comment by marfcg** [comment]
So far, just for testing the functionality, I have retrospectively generated estimates with base_epiweek 23:33 to populate the historical file. That's why we only have those base weeks there.

PS: 32 is not there because of a stupid mistake I made, but it doesn't affect testing so don't worry about it.
