### ISSUE TITLE
Position of label and drop-down menus for dataset selection

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#90]
Is it possible to have the drop-down menus with the same starting x-position?
With either right aligning the labels with respect to the drop-down (as in dataset_menu-proposta.png) or keeping the label as it is and matching the drop-down position (as in dataset_menu-proposta2.png)?

The dashed line in the first is the position to which the labels should be right-aligned (end of text), while on the second one is the position to which the menus should be aligned (start of menus).
![dataset_menu_proposta](https://user-images.githubusercontent.com/8262366/31378629-3a8e41a8-adac-11e7-8a7a-f0457bceb100.png)
![dataset_menu_proposta2](https://user-images.githubusercontent.com/8262366/31378630-3ab2e8be-adac-11e7-9026-970839392558.png)

The first one looks nicer, in my opinion.

**Comment by xmnlab** [comment]
@marfcg .. I will take a look :+1:

**Comment by xmnlab** [comment]
@marfcg 

![layout](https://user-images.githubusercontent.com/5209757/31392200-a948f47c-ada6-11e7-8a44-765fde594288.png)

I like this option because it is the same idea of the field year.

what do you think about this option?
