### ISSUE TITLE
Time series chart - startup week

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#96]
One thing that I forgot on the list of enhancements for the time series: when accessing the web page, the default epiweek should be the most recent for which we have data/estimates.
This would be 

```
epiyear = df_hist.base_epiyear[
    (df_hist.dado == 'srag') &
    (df_hist.escala == 'incidência') & 
    (df_hist.UF == 'BR')
].max()
epiweek = df_hist.base_epiweek[
    (df_hist.dado == 'srag') &
    (df_hist.escala == 'incidência') & 
    (df_hist.UF == 'BR')
].max()
```

Where df_hist is the historical estimates file

**Comment by xmnlab** [comment]
@marfcg 

ok .. I will take a look!

**Comment by xmnlab** [comment]
done.
