### ISSUE TITLE
Improve performance and create a temporary database

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#97]
@marfcg 

Maybe to improve the performance we should create a temporary sqlite database from csv for each time the app is started.

And we maybe could normalize this data.

And all (or almost) filters should be done in sql level ... so I think we will improve the performance a lot 

What do you think?

**Comment by marfcg** [comment]
Absolutely!

Do you have a structure in mind?

One possibility would be:
- One table for location id (unique keys*) and their full name, for state and regions;
- One with incidence and case counts, with location id, epiweek, and epiyear;
- One with columns gender and age brackets, with location, epiweek and epiyear;
- One with historical estimates (this also includes current situation for both estimated and unknowns), with location, epiweek, epiyear, base_epiweek, base_epiyear;

The situation column should be placed on the incidence and case counts or on a table by itself?

\* By the way, currently the ids are a mix of integers and strings. Should I come up with a number for the proposed regional areas? The official ones are the first digit of the states, but the aggregation we proposed would need to be something else entirely. The country as a whole is the single digit 1.

**Comment by xmnlab** [comment]
> Do you have a structure in mind?
I think in first time just replicate into the data base and adjust the code ... but we can do it all at once.

> One possibility would be:

It seems great!

> The situation column should be placed on the incidence and case counts or on a table by itself?

I think we can have a situation table when each situation has an ID number and we can use this on the incidence an case counts table.

> * By the way, currently the ids are a mix of integers and strings. Should I come up with a number for the proposed regional areas? The official ones are the first digit of the states, but the aggregation we proposed would need to be something else entirely. The country as a whole is the single digit 1.

The best approach generally use number .. but we can use a string column, so it would be "1" instead 1 ...

If you find easy to create numerical IDs for these string IDs ... it is ok ... if not .. we can use string ids at this moment.

**Comment by marfcg** [comment]
@xmnlab check this branch: https://github.com/FluVigilanciaBR/data/tree/sqlite
It's an attempt to solve the present issue. I've added table description on the README. Please let me know if anything is not clear. I have changed some column names to make them clearer as well. Please let me know what you think of it.

**Comment by xmnlab** [comment]
@marfcg 

great! I will take a look :+1:

**Comment by marfcg** [comment]
To facilitate the identification of the new columns:
- From what was historical and current estimates files, which have been translated into tables situacao, serie_temporal and estimativas:
```
df_new.rename(columns={
    'UF': 'código', 'SRAG': 'registros', '50%': 'mediana', '2.5%': 'limite inferior',
    '97.5%': 'limite superior', 'L0': 'baixa', 'L1': 'epidêmica', 'L2': 'alta',
    'L3': 'muito alta', 'Run date': 'data de execução', 'Situation': 'situação',
}, inplace=True)
```
- From report, typical, and clean_data_epiweek (the one used for the age and gender distribution) the only change is from 'UF' to 'código'

**Comment by xmnlab** [comment]
@marfcg 

great!

thanks!

**Comment by marfcg** [comment]
@xmnlab a few questions regarding the database:

- Do you believe it would be better to separate the datasets (srag, sragflu, and obitoflu) and the scale (casos, incidência) into tables of their own? Separating them would go into the direction of normalization, right? Would we benefit from it here? 
- Should the column "situação" be given integer values and have another table with columns situation_id | description ?
- If datasets and scale are kept as they are now, that is, without creating separate tables/views for each, the same question regarding column "situação" would apply to those two columns: keep the explicit description as column value or create a new table with dataset_id | description and another with scale_id | description ?

**Comment by xmnlab** [comment]
> Do you believe it would be better to separate the datasets (srag, sragflu, and obitoflu) and the scale (casos, incidência) into tables of their own? Separating them would go into the direction of normalization, right? Would we benefit from it here?

If you want to know more about database normalization, take a look here: https://www.essentialsql.com/get-ready-to-learn-sql-database-normalization-explained-in-simple-english/

In practice, you should think what is the best choice for achieve your goals ... there is some differences between conceptual/logical database structure and "physical" (deploy) 

if we would continue using csv .. maybe would be better use separated csv ... but if we use some database ... it is "more normalized" using all in one table (in this case).

> Should the column "situação" be given integer values and have another table with columns situation_id | description ?

yes! or use ENUM field when available in the database ... there is no enum field type in sqlite database (https://stackoverflow.com/questions/5299267/how-to-create-enum-type-in-sqlite)

> If datasets and scale are kept as they are now, that is, without creating separate tables/views for each, the same question regarding column "situação" would apply to those two columns: keep the explicit description as column value or create a new table with dataset_id | description and another with scale_id | description ?

I didn't understand the question .. but the structure is good but should be better to change string key values (dataset, scale, situation, type, state country) all to integer .. it is lighter and faster

**Comment by xmnlab** [comment]
also it would be good to change the field names to english, change space to underscore and avoid to use symbols in the name. And use all character in lowercase ..

**Comment by xmnlab** [comment]
would be good to change SRAG field name? or is this a good name regarding all dataset and scale attributes?

**Comment by marfcg** [comment]
> it would be good to change SRAG field name? or this name is a good name regarding all dataset and scale?

SRAG is definitely NOT a good field name, since it is a specific dataset. It was kept on the csv just to have the introduction of SRAGFLU and OBITOFLU faster with the working system that already looked at the column SRAG. Thatś  why I changed it to "registros" in the sqlite db.

>also it would be good to change the field names to english, change space to underscore and avoid to use symbols in the name.

Although I agree in principle, for this particular purpose I have mixed feelings about it. The thing is: we are focusing on a product for public health agents in Brazil, which could be implemented by others. The later would naturally lead to adopting English as the standard language, as we are doing with the repo here. The former suggests adoption of Portuguese in the database for ease of access to Brazilian professionals.  @fccoelho and @ogcruz what are your takes on this one?
Regarding special characters and space: I agree.

- Normalization:
From what I read (that page was one of the materials I read, actually), I assumed that breaking it down to tables for each time series (srag, sragflu, obitoflu) was what it was all about... oops. So we should keep the data tables as they are on the sqlite database, right?

- csv vs db:
Database, no question. csv was a quick and dirty way to go since it was what I had the knowledge to implement right away. But it is definitely NOT what we want as a final product. The database is.

- Situação, dado, escala -- ENUM:
Got it. I'll create tables with integer ids for each and convert text to integer for those columns. I still have to come up with a sensible way of translating the regions to numbers as well, so that locations are also uniquely identified by numbers and not by a mixture of numbers and abbreviations.

**Comment by xmnlab** [comment]
> SRAG is definitely NOT a good field name, since it is a specific dataset. It was kept on the csv just to have the introduction of SRAGFLU and OBITOFLU faster with the working system that already looked at the column SRAG.

OK!

> The former suggests adoption of Portuguese in the database for ease of access to Brazilian professionals.

I see .. well so if we will use in portuguese so, would be good all fields in portuguese (with no accent, IMHO) ...

> From what I read (that page was one of the materials I read, actually), I assumed that breaking it down to tables for each time series (srag, sragflu, obitoflu) was what it was all about... oops. So we should keep the data tables as they are on the sqlite database, right?

Actually I think that dataset and scale should be part of the primary key so the table would be normalized.

> Situação, dado, escala -- ENUM:

OK, sqlite doen't support enum (we can treat this in code ... it is not the best approach) ... 

sqlite doesn't support datetime format ...

what do you think to use postgresql? we can upload the database dump into the data repo ... what do you think? or we can upload the database dump into a data repository as dataverse ... I have never used this before ... but seems to be more "scientific", with DOI .. indexing .. etc

**Comment by xmnlab** [comment]
> Got it. I'll create tables with integer ids for each and convert text to integer for those columns. I still have to come up with a sensible way of translating the regions to numbers as well, so that locations are also uniquely identified by numbers and not by a mixture of numbers and abbreviations.

you could use for regions numbers from another range number ... e.g. 
```
    100001 - 'Brasil',
    100002 - 'Regional Centro',
    100003 - 'Regional Leste',
    100004 - 'Regional Norte',
```

**Comment by xmnlab** [comment]
I will try to write a notebook with an initial migration (IMHO) so you can change it with your own point of view.

**Comment by xmnlab** [comment]
https://github.com/xmnlab/fludashboard/blob/development/Notebooks/Dataset-Migration.ipynb

**Comment by xmnlab** [comment]
@marfcg 

I am checking the tables structure and I am realizing that are some fields duplicated across the tables ...

I have some questions: 

Seems like incidence [1] and historical [2] tables have these columns (and their values) repeated:

- value, situation_id, run_date

Seems like mem_typical and mem_report tables have these columns (and their values) repeated:

- population

Is there any reason to have these columns (and values) repeated?

[1] current_estimated_values
[2] historical_estimated_values

**Comment by marfcg** [comment]
Good catch!

- mem_typical and mem_report:
Column 'population' was useful for standalone csv's. As database tables, they're not needed. I have a file with population by age bracket, per location, per year, that will be a table on it's own. Therefore, those columns can be discarded from the tables.

For tables [1] and [2], those columns do not have the same values necessarily and should be kept in each.

- current_estimated_values:
Columns 'value' and 'situation_id' have their most recent data, based on run_date.
  - 'value' is the most recent count for the corresponding week, based on run_date.
  - 'situation_id' is the situation of the corresponding week based on run_date.

- historical_estimated_values:
Columns 'value' and 'situation_id' have their data as they were on (base_epiyear, base_epiweek), with estimates generated on run_date.

In addition, for the table corresponding to file current_estimated_values there is no need to keep columns L0, L1, L2 and L3. We could keep a single column dubbed 'level' which would take values 0,1,2,3 according to the column with highest value. Column 'level' from current_estimated_values would be then used to define map color.

That same column should also be present on historical_values, and would then hold the level estimated at time (base_epiyear, base_epiweek).

What do you think?

**Comment by xmnlab** [comment]
> I have a file with population by age bracket, per location, per year, that will be a table on it's own.

great! Can you add this table into a csv?

> In addition, for the table corresponding to file current_estimated_values there is no need to keep columns L0, L1, L2 and L3. We could keep a single column dubbed 'level' which would take values 0,1,2,3 according to the column with highest value. Column 'level' from current_estimated_values would be then used to define map color.
> That same column should also be present on historical_values, and would then hold the level estimated at time (base_epiyear, base_epiweek).

Great! I am finishing the first version of the app using postgresql today ... next week I will work on these changes.

**Comment by marfcg** [comment]
PS, for clarity: in the historical table we need to keep columns L0, L1, L2 and L3, since it holds the calculated probability of falling in each category. This info is always shown on the time series panel.

**Comment by xmnlab** [comment]
> This info is always shown on the time series panel.

how?

**Comment by marfcg** [comment]
It's currently being presented on the top left corner of the graph.


---
*Sent from mobile device. My apologies for eventual typos.
Marcelo Ferreira da Costa Gomes
Programa de Computação Científica
Fundação Oswaldo Cruz
PROCC/FIOCRUZ

**Comment by xmnlab** [comment]
ah ok :) thanks!

**Comment by xmnlab** [comment]
@marfcg 

I will check your last recommendation, thanks.

**Comment by xmnlab** [comment]
the last recommendation will be analysed at https://github.com/FluVigilanciaBR/fludashboard/issues/113
