### ISSUE TITLE
Question: notebooks and prototype folders

### ISSUE THREAD

**Issue by marfcg** [FluVigilanciaBR/fludashboard#98]
Question from a newbie in terms of structuring files and branches for release.
The central point of folders Notebooks/ and prototype/ is to helps us through dev, right? That is, they are not needed for production. It doesn't hurt to have them there, but they are not needed either.

So,
a) Should we create separate branches to keep them (e.g. one dubbed notebooks and one dubbed prototypes, which would be kept on par with the development branch, but with those extra folders)?
b) Should we create a release branch where we strike them out? 
c) Or keep it as it is.

To me it seems natural to go for option (a). But I would like to have some feedback from you, who are way more familiar to this environment than I am.

Thanks!

**Comment by xmnlab** [comment]
@marfcg 

it is a good question. Actually I like to think this folders as part of the documentation. So, I think it is better to keep them into the branch (master and development) 

for production environment, I think to create a package pypi and conda and, to prepare the environment, we just install the package fludashboard (and automatically will install its dependencies).

And in the package creation, we can omit the prototype and notebooks folders.

For conda package creation, it is necessary to create a version tag for each version.

What do you think?

**Comment by marfcg** [comment]
Sounds great.

In this scenario, at the server we would only install the package itself, without cloning the main branch.
So, what we need is then to create those packages from the current stable version (main branch).

We could tag it now with v0.3 and, once #96 is completed we move to 0.3.1.
Or, wait for that issue to be closed before tagging and building the package.

Have I got it right?

**Comment by xmnlab** [comment]
yes!

The version in fludashboard.__init__.py is already set to 0.3.0

but before create the tag, I need to test the setup install locally.

When it is done I can create the tag 0.3.0

ok?

**Comment by xmnlab** [comment]
@marfcg 

I need to set these information on setup.py:

```
author="XXXXX XXXXX XXXXX",
author_email='xxxxxxxx@xxxxxxx.xxxx',
```

What should I put there?

**Comment by xmnlab** [comment]
about the data 

What is the frequency that these data should be updated?

maybe should be better to remove the data from the project and add them into another repo.

and we can upload the data when the app is started, or something like that.

**Comment by marfcg** [comment]
Ideally, they will be updated every week.
They are generated by the seasonality tool, and stored here:
https://github.com/FluVigilanciaBR/seasonality/tree/master/methods/clean_data

Every time they are generated, I copy them to fludashboard/data.
As I've mentioned a while ago, the end goal is to actually have seasonality writing them to a database which is then read by fludashboard. Unfortunately, I haven't had the time -- nor the knowledge -- to define the database structure yet.

So, in the meanwhile, we can safely remove the data folder from fludashboard repo.
It seems to me that an alternative is to create a data repo within FluVigilanciaBR, and use it as a submodule in seasonality.
In this way, the data will be in its own repo, seasonality will be able to update it easily, and fludashboard will have a clean way to accessing it.

What do you think?

**Comment by xmnlab** [comment]
> So, in the meanwhile, we can safely remove the data folder from fludashboard repo.
It seems to me that an alternative is to create a data repo within FluVigilanciaBR, and use it as a submodule in seasonality.
> In this way, the data will be in its own repo, seasonality will be able to update it easily, and fludashboard will have a clean way to accessing it.

great! :+1: 

> As I've mentioned a while ago, the end goal is to actually have seasonality writing them to a database which is then read by fludashboard. Unfortunately, I haven't had the time -- nor the knowledge -- to define the database structure yet.

maybe we can start using a sqlite ... a very simple database .. we can write a script to migrate from csv to sqlite and make some normalization. If the performance is ok, we can keep with this, if not, we can think to export to postgresql.

what do you think?

to create or package I need the author's name and author_email ... what should I put there?

**Comment by marfcg** [comment]
Well, the creators are basically you and me, I believe.
@fccoelho also helped discussing the layout. He can also be part of the list. What do you say, Flavio?
From my part, you can put my institutional email: marcelo.gomes@fiocruz.br

**Comment by marfcg** [comment]
Data repo:
https://github.com/FluVigilanciaBR/data

Files are inside `data/` folder on that repo.
